x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    DBT_PROFILES_DIR: /opt/airflow/dbt
    DW_HOST: postgres-dw
    DW_PORT: 5432
    DW_USER: ${DW_USER}
    DW_PASSWORD: ${DW_PASSWORD}
    DW_DBNAME: ${DW_DBNAME}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./dbt:/opt/airflow/dbt
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  depends_on:
    - postgres-airflow
    - postgres-dw

services:
  # Banco de metadados interno do Airflow (não é o DW do projeto)
  postgres-airflow:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-airflow-volume:/var/lib/postgresql/data

  #  Postgres Data Warehouse 
  postgres-dw:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DW_USER}
      POSTGRES_PASSWORD: ${DW_PASSWORD}
      POSTGRES_DB: ${DW_DBNAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres-dw-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DW_USER} -d ${DW_DBNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  create-schemas:
    image: postgres:15
    depends_on:
      postgres-dw:
        condition: service_healthy
    environment:
      PGPASSWORD: ${DW_PASSWORD}
    volumes:
      - ./postgres-init:/scripts
    entrypoint: /bin/bash
    command:
      - -c
      - |
        psql -h postgres-dw -U ${DW_USER} -d ${DW_DBNAME} -f /scripts/create_schemas.sql

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username admin \
          --firstname admin \
          --lastname admin \
          --role Admin \
          --email admin@example.com \
          --password admin

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  # Web interface for Postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"
    depends_on:
      - postgres-dw
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-airflow-volume:
  postgres-dw-volume:
  pgadmin-data: