-- Creating Schemas 

CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;

-- Grant access to the Schemas

GRANT ALL ON SCHEMA bronze TO CURRENT_USER;
GRANT ALL ON SCHEMA silver TO CURRENT_USER;
GRANT ALL ON SCHEMA gold TO CURRENT_USER;